[client] Refactoring
mmogo/mmo pull request #16
Opened 2017-07-01 01:20 UTC by aerth

This PR is a work in progress

- [x] Move global vars into a `GameWorld` struct

- [x] create methods from old functions

- [ ] fix conflicts from #15 (done, not commited)

- [ ] create `GameWorld.ApplyUpdate(*Update)`

2017-07-01 23:52 UTC, aerth commented on client/main.go
> +	animationRate := 1.0 // framerate of player animation
slow down animation to 1 fps, seems to help with jitter for now (until changing player sprite)

2017-07-01 23:55 UTC, aerth commented on client/main.go
> +func (g *GameWorld) ApplyUpdate(update *shared.Update) {
I scrapped the `switch` so that updates can have more than one update type in the future

2017-07-01 23:57 UTC, aerth commented on server/main.go
> +			if strings.HasPrefix(err.Error(), "fatal") {
Only quit server if "fatal" errors ( currently only if cant listen on udp port )

2017-07-01 23:58 UTC, aerth commented on server/main.go
> +	if len(clientChecksums) > 0 {
only serve tcp if at least 1 client to serve

2017-07-02 19:33 UTC, ilackarms requested changes
see comments

2017-07-02 19:33 UTC, ilackarms commented on server/main.go
> +			if strings.HasPrefix(err.Error(), "fatal") {
i like it. maybe what we can do here is 

```go
switch err.(type){
    case fatalErr:
       log.Fatal(err)
   default:
       log.Println("err: ", err)
}
```

and then define an error type `fatalErr` which we can return

i just prefer this pattern than having to remember to put the prefix `fatal` onto a string

2017-07-02 19:33 UTC, ilackarms commented on server/main.go
> +	if msg.Request == nil || msg.Request.ConnectRequest == nil {
unneceessary nil check (if err == nil, msg is not nil)

2017-07-02 19:33 UTC, ilackarms commented on server/main.go
> +					clientfile, err := os.Open(client)
let's use `http.ServeFile` here which will handle for us all the edge cases (proper headers, handling errors, etc.)

2017-07-02 19:33 UTC, ilackarms commented on server/main.go
> +	if len(clientChecksums) > 0 {
:+1:

2017-07-02 19:33 UTC, ilackarms commented on server/main.go
> +	// check if in use
uncomment or delete? this is a good check to have

2017-07-02 19:33 UTC, ilackarms commented on server/main.go
> +	// echo back connect message
why do we echo back?

2017-07-02 19:33 UTC, ilackarms commented on client/main.go
> +	msg, err := shared.GetMessage(conn)
what's the purpose of this?

2017-07-02 19:33 UTC, ilackarms commented on server/main.go
> +		if msg.Request != nil {
msg should never be nil

2017-07-02 19:33 UTC, ilackarms commented on server/main.go
> +			errc <- err
nice
we can remove the TODO here

2017-07-02 19:33 UTC, ilackarms commented on server/main.go
> +			if msg.Request != nil {
remove

2017-07-02 19:33 UTC, ilackarms commented on server/main.go
> +		})
i don't understand the purpose of this block. if `ok == false`, then `delete(players, id)` is noop

also, unless there is a bug somewhere in the program, `ok` should never `== true` if the player is still connected. if a player disconnects, we should handle the disconnect when it occurs (queue the update notify player disconnected *then*, not wait til this loop to catch it)

i'd be in favor of removing this whole block

2017-07-02 20:49 UTC, aerth commented on client/main.go
> +	msg, err := shared.GetMessage(conn)
to confirm connection to server before drawing window

2017-07-02 20:51 UTC, ilackarms approved these changes

2017-07-02 20:52 UTC, merged